---
# Глобальные настройки DHCP
dhcp_server_domain_name: dhcp.example.org #"{{ inventory_hostname }}.example.org"
dhcp_server_dns_servers: [ns1.example.org, ns2.example.org]
dhcp_server_default_lease_time: 600
dhcp_server_max_lease_time: 7200
dhcp_server_authoritative: true
dhcp_server_log_facility: local7

# Настройки для каждой подсети
dhcp_server_subnets:
  - ip: 10.1.1.0
    netmask: 255.255.255.0
    range_start: 10.1.1.2
    range_end: 10.1.1.254
    broadcast_address: 10.1.1.255
    routers: 10.1.1.1

# Все доступные опции настройки подсети
# - ip:
#   netmask:
#   range_start:
#   range_end:
#   domain_name:
#   dns_servers:
#   routers:
#   broadcast_address:
#   default_lease_time:
#   max_lease_time:

# Настройки сетевых интерефесов DHCP сервера для Multihomed DHCP
# Может быть полезно когда сервера обслуживает несколько подсетей на разных интерфейсах
# В примере ниже параметры настройки интерфейса получают изначения из модуля setup
# dhcp_server_interfaces:
#   - name: "{{ ansible_default_ipv4.interface }}"
#     mac: "{{ ansible_default_ipv4.macaddress }}"
#     fixip: "{{ ansible_default_ipv4.address }}"

# Все доступные опцие настройки интерфесов
#   - name:
#     mac:
#     fixip:
