---
# Проверяем версию RHEL/CentOS и если версия 7 или меньше, то пакет dhcp, если больше то dhcp-server
dhcp_package_name: "{{ 'dhcp' if (ansible_distribution_major_version <= '7') else 'dhcp-server' }}"
